version: "3.9"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file: postgres.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: ["postgres"]
    networks:
      - postgres_network

volumes:
  postgres_volume:

networks:
  postgres_network: